name: CI Analyse-trafic Service

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'ms-analyse-trafic/**'
      - '.github/workflows/ci_analyse_trafic.yml'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'ms-analyse-trafic/**'
      - '.github/workflows/ci_analyse_trafic.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest

      # Step to install Flake8 and run linting
      - name: Install Flake8
        run: |
          poetry add --dev flake8
          poetry run flake8 .

  sonarqube:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORG }}
          token: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ms-analyse-trafic:latest ms-analyse-trafic